# Generated by Django 3.0.7 on 2020-06-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=50, unique=True)),
                ('showing_name', models.CharField(max_length=50)),
                ('ordering', models.FloatField()),
            ],
            options={
                'ordering': ['-ordering'],
            },
        ),
    ]
