# Generated by Django 3.0.7 on 2020-07-31 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200731_2028'),
        ('board', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentalertcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_name', models.CharField(max_length=300)),
                ('view', models.BooleanField(default=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Comment')),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
