# Generated by Django 3.0.7 on 2020-08-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200731_2028'),
        ('board', '0006_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='group', to='account.Profile'),
        ),
    ]
