# Generated by Django 2.2.1 on 2020-08-16 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_board_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='author',
            field=models.ForeignKey(default='탈퇴회원', on_delete=django.db.models.deletion.SET_DEFAULT, to='account.Profile'),
        ),
    ]
