# Generated by Django 3.0.7 on 2020-06-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secure', models.CharField(blank=True, choices=[('public', '공개'), ('private', '비공개')], max_length=7, null=True)),
                ('title', models.CharField(max_length=50)),
                ('information', models.TextField()),
                ('cord_sx', models.IntegerField(blank=True, null=True)),
                ('cord_sy', models.IntegerField(blank=True, null=True)),
                ('cord_lx', models.IntegerField(blank=True, null=True)),
                ('cord_ly', models.IntegerField(blank=True, null=True)),
                ('important', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='board_picture/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
            ],
            options={
                'ordering': ['-important'],
            },
        ),
    ]
