# Generated by Django 3.0.7 on 2020-07-03 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200630_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='post_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root', to='board.Board'),
        ),
    ]
