# Generated by Django 3.0.7 on 2020-07-31 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Commentalert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent', models.IntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
    ]
